### ISSUE TITLE
Feature Request Webapp: Slider

### ISSUE THREAD

**Issue by luecu** [sbb-design-systems/design-system-webapp-documentation#10]
**Is your feature request related to a problem? Please describe.**
For business applications I was often looking for a Slider Component to easily adjust number values in an UX friendly way.

**Describe the solution you'd like**
Something like: https://primefaces.org/primeng/showcase/#/slider

**Describe alternatives you've considered**
https://primefaces.org/primeng/showcase/#/slider

**Comment by Frenggi** [comment]
Thank you for the request and sorry for the late reply. We will take it to the backlog for a future update of the design system.
